const SEED = [
  {
    "id": "accede-mold-tool",
    "company": "Accede Mold & Tool",
    "website": "https://accedemold.com/",
    "score": 4,
    "status": "QA Review",
    "reason": "Strong manufacturing fit; revenue and current urgency are not verified, so the earlier 5/5 is revised to 4/5.",
    "route": "Possible direct owner/president route; Jeff must confirm contact and any warm path.",
    "contact": "Roger Fox, described in Accede company sources as owner/president; current channel not confirmed.",
    "report": "https://github.com/CoachAGP/jeff-outreach-engine/blob/main/docs/discovery/opportunity-report-accede-mold-tool.md",
    "summary": "Verified: precision moldmaking and systems integration in Rochester, NY. Earlier ZoomInfo Cost Control score 99 is an undated source-provided indicator, not confirmed current buying intent. Indirect supplier categories are hypotheses. Joe HubSpot had no company match; Jeff's conflict check is pending.",
    "sources": "https://accedemold.com/about-us/ (company, leadership); https://accedemold.com/plastics_fall_conference_2023/ (Roger Fox role); prior ZoomInfo intent email (undated indicator). Checked 2026-09-22.",
    "conflicts": "",
    "qa": "Pass",
    "hubspotReviewed": "",
    "hubspotFinding": "Connected Joe HubSpot: no company match by name or domain; no named-contact match. Jeff's HubSpot and Athena not checked. No record written.",
    "draftSubject": "Quick question about Accede Mold & Tool",
    "draft": "Hello Roger,\n\nI work with ERA Group, helping organizations review indirect supplier spend with deep category expertise and no upfront cost. I came across Accede's work in precision moldmaking and systems integration and thought there might be a useful conversation.\n\nAre you the right person to ask whether a brief discussion about operating supplier costs would be relevant, or would someone on your finance or operations team be better?\n\nBest,\nJeff Peduto",
    "draftStatus": "Draft awaiting separate approval",
    "note": "Confirm Roger's current role/channel; Jeff must check his HubSpot and Athena, resolve conflict status, and approve any communication.",
    "revision": 0,
    "history": [{"requestId":"pilot-accede-20260922","at":"2026-09-22T16:07:00Z","actor":"Codex (Joe workspace)","from":"Pilot intake","to":"QA Review","note":"Sourced report and draft prepared; Jeff checks pending."}]
  },
  {
    "id": "delcath-systems",
    "company": "Delcath Systems",
    "website": "https://delcath.com/",
    "score": 5,
    "status": "QA Review",
    "reason": "U.S. healthcare manufacturer with reported $29.1M Q2 2026 revenue and a current commercial expansion signal; indirect spend remains unverified.",
    "route": "Possible direct finance route; Jeff must confirm contact and relationship status.",
    "contact": "Sandra Pennell, CFO identified in August 2026 SEC filing; contact channel not confirmed.",
    "report": "https://github.com/CoachAGP/jeff-outreach-engine/blob/main/docs/discovery/opportunity-report-delcath-systems.md",
    "summary": "Verified: Delcath reported $29.1M Q2 2026 revenue and 31 active treatment centers. The September 12 ZoomInfo lists estimate 156 employees and $95.418M revenue; they contain no specific intent score. Joe HubSpot had no company match; Jeff's conflict check is pending.",
    "sources": "https://investors.delcath.com/news-releases/news-release-details/delcath-systems-reports-second-quarter-2026-results-and-business (Q2 results); https://investors.delcath.com/node/19131/html (CFO); user-supplied Sept 12 ZoomInfo CSVs, ID 10879082. Checked 2026-09-22.",
    "conflicts": "",
    "qa": "Pass",
    "hubspotReviewed": "",
    "hubspotFinding": "Connected Joe HubSpot: no company match by name or domain; no named-contact match. Jeff's HubSpot and Athena not checked. No record written.",
    "draftSubject": "Quick question about Delcath",
    "draft": "Hello Sandra,\n\nI work with ERA Group, helping organizations review indirect supplier spend with deep category expertise and no upfront cost. I saw Delcath's recent update on its expanding treatment-center network and thought a short finance-side conversation might be useful.\n\nAre you the right person to ask whether a discussion about operating supplier costs would be relevant, or is there someone else on your team I should speak with?\n\nBest,\nJeff Peduto",
    "draftStatus": "Draft awaiting separate approval",
    "note": "Confirm CFO role/channel; Jeff must check his HubSpot and Athena, resolve conflict status, and approve any communication.",
    "revision": 0,
    "history": [{"requestId":"pilot-delcath-20260922","at":"2026-09-22T16:07:00Z","actor":"Codex (Joe workspace)","from":"Pilot intake","to":"QA Review","note":"Sourced report and draft prepared; Jeff checks pending."}]
  },
  {
    "id": "angiodynamics",
    "company": "AngioDynamics",
    "website": "https://www.angiodynamics.com/",
    "score": 5,
    "status": "QA Review",
    "reason": "U.S. medical-technology manufacturing fit; company-reported $320.2M FY2026 pro forma sales and Med Tech growth, with indirect spend still unverified.",
    "route": "Possible direct finance route; Jeff must confirm contact and relationship status.",
    "contact": "Stephen Trowbridge, EVP and CFO in June 2026 company release; current channel not confirmed.",
    "report": "https://github.com/CoachAGP/jeff-outreach-engine/blob/main/docs/discovery/opportunity-report-angiodynamics.md",
    "summary": "Verified: AngioDynamics reported $320.2M FY2026 pro forma net sales and $150.0M Med Tech sales. The September 12 ZoomInfo lists estimate 632 employees but provide no specific intent score. Joe HubSpot had no exact-domain company match; Jeff's conflict check is pending.",
    "sources": "https://investors.angiodynamics.com/news-releases/news-release-details/angiodynamics-reports-record-fiscal-year-2026-fourth-quarter-and (FY2026 results); https://investors.angiodynamics.com/node/23481 (CFO); user-supplied Sept 12 ZoomInfo CSVs, ID 15569419. Checked 2026-09-22.",
    "conflicts": "",
    "qa": "Pass",
    "hubspotReviewed": "",
    "hubspotFinding": "Connected Joe HubSpot: no exact-domain company match; no named-contact match. Jeff's HubSpot and Athena not checked. No record written.",
    "draftSubject": "Quick question about AngioDynamics",
    "draft": "Hello Stephen,\n\nI work with ERA Group, helping organizations review indirect supplier spend with deep category expertise and no upfront cost. I saw AngioDynamics' recent fiscal-year update and its Med Tech growth and thought there might be a useful finance-side conversation.\n\nAre you the right person to ask whether a brief discussion about operating supplier costs would be relevant, or would someone else on your team be better?\n\nBest,\nJeff Peduto",
    "draftStatus": "Draft awaiting separate approval",
    "note": "Confirm CFO role/channel; Jeff must check his HubSpot and Athena, resolve conflict status, and approve any communication.",
    "revision": 0,
    "history": [{"requestId":"pilot-angio-20260922","at":"2026-09-22T16:07:00Z","actor":"Codex (Joe workspace)","from":"Pilot intake","to":"QA Review","note":"Sourced report and draft prepared; Jeff checks pending."}]
  }
]
;
